databases:
  - name: climatedb
    plan: free
    databaseName: climatic
    user: climaticuser

services:
  - type: web
    name: airinua-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: climatedb
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_LOG_LEVEL
        value: "DEBUG"
      - key: DJANGO_SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DJANGO_ALLOWED_HOSTS
        value: "www.airinua.com,airinua.com"
      - key: DEBUG
        value: "True"
      - key: EMAIL_HOST_USER
        value: "your_email_user"
        sync: false
      - key: EMAIL_HOST_PASSWORD
        value: "your_email_password"
        sync: false
      - key: ADMIN_EMAIL
        value: "your_admin_email"
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "your_default_from_email"
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: "your_cloud_name"
        sync: false
      - key: CLOUDINARY_API_KEY
        value: "your_api_key"
        sync: false
      - key: CLOUDINARY_API_SECRET
        value: "your_api_secret"
        sync: false
      - key: STATIC_URL
        value: "/static/"
      - key: STATIC_ROOT
        value: "staticfiles"
      - key: MEDIA_URL
        value: "/media/"
      - key: MEDIA_ROOT
        value: "media" 