databases:
  - name: mysitedb # Ви можете змінити це ім'я
    plan: free # Або інший план, якщо потрібно
    databaseName: mysite # Назва бази даних
    user: mysiteuser # Ім'я користувача БД

services:
  - type: web
    name: climat-app # Назва вашого сервісу на Render (використав climat-app)
    runtime: python
    plan: free # Або інший план
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn config.wsgi:application" # Спочатку міграції, потім запуск
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb # Має збігатися з 'name' у секції databases
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true # Render згенерує випадковий ключ
      - key: WEB_CONCURRENCY
        value: 4 # Рекомендоване значення, можна налаштувати
      - key: PYTHON_VERSION
        value: "3.11.9" # Вказано повну версію для Render
      - key: DJANGO_LOG_LEVEL
        value: "INFO"
      - key: DJANGO_SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DJANGO_ALLOWED_HOSTS
        value: "www.airinua.com,airinua.com"
      # Обов'язково додайте ваші змінні для пошти та інші сюди або в панелі Render:
      # - key: DJANGO_ALLOWED_HOSTS
      #   value: "your-app-name.onrender.com" # Замініть your-app-name
      # - key: EMAIL_HOST_USER
      #   value: "your_email_user"
      # - key: EMAIL_HOST_PASSWORD
      #   sync: false # Для секретів краще встановлювати через панель Render
      # - key: ADMIN_EMAIL
      #   value: "your_admin_email"
      # - key: DEFAULT_FROM_EMAIL
      #   value: "your_default_from_email" 