# Generated by Django 5.2 on 2025-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airinua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматично генерується з назви товару', max_length=255, null=True, unique=True, verbose_name='URL slug'),
        ),
    ]
