# Generated by Django 4.2.23 on 2025-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airinua', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, help_text='Наприклад: img/service.png', max_length=255, null=True, verbose_name='Шлях до зображення'),
        ),
    ]
