# Generated by Django 5.2 on 2025-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airinua', '0004_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL зображення з Cloudinary або іншого хмарного сервісу', max_length=500, null=True, verbose_name='URL зображення'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL зображення з Cloudinary або іншого хмарного сервісу', max_length=500, null=True, verbose_name='URL зображення'),
        ),
    ]
